version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-network
  odoo:
    image: odoo:16.0
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    command: >
      bash -c "
        mkdir -p /var/lib/odoo/.local/share/Odoo/sessions &&
        /entrypoint.sh odoo
      "
    networks:
      - odoo-network

volumes:
  postgres-data:
  odoo-data:

networks:
  odoo-network: